Repository BarbzCodez/Spendr, pull requests merged in 2023-12, with the labels that each got.

#164 Added documentation for defining coding standard
  documentation/development.md
Labels: documentation

#166 Dynamic API URLs
  client/src/api/BudgetAPI.ts
  client/src/api/ExpenseAPI.ts
  client/src/api/GroupExpensesAPI.ts
  client/src/api/UserAPI.ts
Labels: frontend

#165 Release summary fixes
  documentation/release-summary.md
Labels: documentation

#167 Spendr logo in documentation files
  README.md
  documentation/images/spndr_logo.png
  documentation/release-summary.md
Labels: documentation

#168 Run production client build instead of development server in Docker
  client/Dockerfile
Labels: infrastructure

#169 Added /api prefix to all API endpoints
  client/src/api/BudgetAPI.ts
  client/src/api/ExpenseAPI.ts
  client/src/api/GroupExpensesAPI.ts
  client/src/api/UserAPI.ts
  documentation/test-plan.md
  server/src/app.ts
  server/src/test/integration/budgets/createBudget.test.ts
  server/src/test/integration/expenses/createExpense.test.ts
  server/src/test/integration/expenses/deleteExpense.test.ts
  server/src/test/integration/groupExpenses/createGroupExpense.test.ts
  server/src/test/integration/groupExpenses/markGroupExpenseAsPaid.test.ts
  server/src/test/integration/users/deleteUser.test.ts
  server/src/test/integration/users/login.test.ts
  server/src/test/integration/users/register.test.ts
  server/src/test/integration/users/resetPassword.test.ts
  server/src/test/integration/users/updateUser.test.ts
  server/src/test/unit/routes/budgets.test.ts
  server/src/test/unit/routes/expenses.test.ts
  server/src/test/unit/routes/groupExpenses.test.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend

#170 Add environment variables to client image build
  .github/workflows/cd.yml
Labels: infrastructure

#172 Add key features to readme
  README.md
Labels: documentation

#171 Set client environment variables for docker build
  .github/workflows/cd.yml
  client/Dockerfile
Labels: infrastructure

#173 Replace Docker ENV usage with ARG
  .github/workflows/cd.yml
  client/Dockerfile
Labels: infrastructure
