Repository BarbzCodez/Spendr, pull requests merged in 2023-11, with the labels that each got.

#119 Fetch, create group expenses and mark as paid
  server/prisma/migrations/20231103003844_main/migration.sql
  server/prisma/migrations/20231104160120_main/migration.sql
  server/prisma/schema.prisma
  server/src/app.ts
  server/src/routes/auth.ts
  server/src/routes/groupExpenses.ts
  server/src/test/unit/routes/auth.test.ts
  server/src/test/unit/routes/groupExpenses.test.ts
  server/src/utils/expenses.ts
Labels: backend, developer task

#121 Add code coverage report to gitignore
  server/.gitignore
Labels: infrastructure

#124 Return 400 on validation errors when updating expense
  server/src/routes/expenses.ts
  server/src/test/unit/routes/expenses.test.ts
Labels: bug, backend

#118 2023 10 23.md
  documentation/meeting-logs/2023-10-23.md
Labels: documentation

#125 2023 10 30
  documentation/meeting-logs/2023-10-30.md
Labels: documentation

#127 Total daily expenses from x to y
  server/src/app.ts
  server/src/routes/users.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend, developer task

#115 Budget Page
  client/src/App.tsx
  client/src/api/BudgetAPI.ts
  client/src/api/ExpenseAPI.ts
  client/src/api/UserAPI.ts
  client/src/assets/styles/theme.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/constants/constants.ts
  client/src/interfaces/interfaces.ts
  client/src/pages/Budgets/Budgets.tsx
  client/src/pages/Budgets/Components/BudgetDialog.tsx
  client/src/pages/Budgets/Components/ProgressBar.tsx
  client/src/pages/Budgets/index.ts
  client/src/pages/Budgets/styles.ts
  client/src/pages/Expenses/Expenses.tsx
Labels: frontend

#128 Added group expense id to get group expense response
  server/src/routes/users.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend

#130 Receipt image parsing and expense form autofill
  client/package-lock.json
  client/package.json
  client/src/api/EdenAPI.ts
  client/src/assets/styles/styles.ts
  client/src/assets/styles/theme.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/interfaces/interfaces.ts
Labels: frontend, backend, developer task

#133 Add Homepage UI
  client/src/interfaces/interfaces.ts
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/constants.tsx
  client/src/pages/Home/styles.ts
Labels: frontend, developer task

#134 Get total expense gategory
  server/src/routes/users.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend

#135 Made analytics endpoints return objects with keys
  server/src/routes/users.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend

#137 Total expense url params
  server/src/routes/users.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend

#138 categories url params
  server/src/routes/users.ts
  server/src/test/unit/routes/users.test.ts
Labels: backend

#136 Integration tests
  documentation/test-plan.md
  server/docker-compose.test.yml
  server/jest.config.js
  server/package.json
  server/run-integration-tests.sh
  server/src/test/integration/budgets/createBudget.test.ts
  server/src/test/integration/expenses/createExpense.test.ts
  server/src/test/integration/expenses/deleteExpense.test.ts
  server/src/test/integration/groupExpenses/createGroupExpense.test.ts
  server/src/test/integration/groupExpenses/markGroupExpenseAsPaid.test.ts
  server/src/test/integration/resetDb.ts
  server/src/test/integration/setup.ts
  server/src/test/integration/users/deleteUser.test.ts
  server/src/test/integration/users/login.test.ts
  server/src/test/integration/users/register.test.ts
  server/src/test/integration/users/resetPassword.test.ts
  server/src/test/integration/users/updateUser.test.ts
Labels: backend, testing

#141 Add Meeting 9 + formatting
  documentation/meeting-logs/2023-10-16.md
  documentation/meeting-logs/2023-10-23.md
  documentation/meeting-logs/2023-10-30.md
  documentation/meeting-logs/2023-11-13.md
Labels: documentation

#131 Group expense ui and hookup
  client/src/App.tsx
  client/src/api/GroupExpensesAPI.ts
  client/src/api/UserAPI.ts
  client/src/assets/styles/theme.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/interfaces/interfaces.ts
  client/src/pages/Expenses/Components/ExpenseTable.tsx
  client/src/pages/Expenses/Expenses.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseDialog.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseTable.tsx
  client/src/pages/GroupExpenses/Components/styles.ts
  client/src/pages/GroupExpenses/GroupExpenses.tsx
  client/src/pages/GroupExpenses/index.ts
  client/src/pages/styles.ts
  client/src/utils/utils.ts
Labels: frontend, developer task

#139 Analytics hook
  client/src/api/UserAPI.ts
  client/src/constants/constants.ts
  client/src/interfaces/interfaces.ts
  client/src/pages/Analytics/Analytics.tsx
  client/src/pages/Analytics/components/CategoryGraph.tsx
  client/src/pages/Analytics/components/CompareGraph.tsx
  client/src/pages/Analytics/components/DailyExpensesGraph.tsx
  client/src/pages/Analytics/components/MonthlyExpensesGraph.tsx
  client/src/pages/Analytics/components/styles.ts
Labels: frontend

#140 fix ui not displaying properly in bigger screens
  client/src/pages/Budgets/Budgets.tsx
  client/src/pages/Budgets/styles.ts
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/styles.ts
  client/src/pages/UserSettings/UserSettings.tsx
  client/src/pages/UserSettings/styles.ts
  client/src/styles.ts
Labels: bug, frontend

#144 UI Cleanup
  client/src/api/BudgetAPI.ts
  client/src/api/EdenAPI.ts
  client/src/api/ExpenseAPI.ts
  client/src/api/GroupExpensesAPI.ts
  client/src/api/UserAPI.ts
  client/src/assets/constants/constants.ts
  client/src/assets/styles/styles.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/components/Header/Header.tsx
  client/src/context/UserContext.tsx
  client/src/interfaces/budgetInterfaces.ts
  client/src/interfaces/expenseInterfaces.ts
  client/src/interfaces/generalInterfaces.ts
  client/src/interfaces/groupSplitInterfaces.ts
  client/src/interfaces/interfaces.ts
  client/src/interfaces/userInterfaces.ts
  client/src/pages/Analytics/components/CategoryGraph.tsx
  client/src/pages/Analytics/components/CompareGraph.tsx
  client/src/pages/Analytics/components/MonthlyExpensesGraph.tsx
  client/src/pages/Budgets/Budgets.tsx
  client/src/pages/Budgets/Components/BudgetDialog.tsx
  client/src/pages/Budgets/Components/ProgressBar.tsx
  client/src/pages/Expenses/Components/ExpenseTable.tsx
  client/src/pages/Expenses/Expenses.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseDialog.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseTable.tsx
  client/src/pages/GroupExpenses/GroupExpenses.tsx
  client/src/pages/Home/constants.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/components/LoginForm.tsx
  client/src/pages/Signup/components/SignupForm.tsx
  client/src/pages/UserSettings/components/DangerZone.tsx
  client/src/pages/UserSettings/components/SettingsListItem.tsx
  client/src/pages/styles.ts
Labels: frontend

#145 More Cleanup to the frontend
  client/src/api/BudgetAPI.ts
  client/src/assets/constants/index.ts
  client/src/assets/styles/index.ts
  client/src/assets/styles/styles.ts
  client/src/assets/utils/index.ts
  client/src/assets/utils/utils.ts
  client/src/components/ExpenseDialog/index.ts
  client/src/context/UserContext.tsx
  client/src/pages/Analytics/components/CategoryGraph.tsx
  client/src/pages/Analytics/components/CompareGraph.tsx
  client/src/pages/Analytics/components/MonthlyExpensesGraph.tsx
  client/src/pages/Budgets/Budgets.tsx
  client/src/pages/Budgets/Components/BudgetDialog.tsx
  client/src/pages/Budgets/Components/ProgressBar.tsx
  client/src/pages/Expenses/Components/ExpenseDialog.tsx
  client/src/pages/Expenses/Components/ExpenseTable.tsx
  client/src/pages/Expenses/Expenses.tsx
  client/src/pages/Greetings/Greetings.tsx
  client/src/pages/Greetings/styles.ts
  client/src/pages/GroupExpenses/Components/GroupExpenseDialog.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseTable.tsx
  client/src/pages/GroupExpenses/GroupExpenses.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/components/LoginForm.tsx
  client/src/pages/Login/styles.ts
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/components/SignupForm.tsx
  client/src/pages/Signup/styles.ts
  client/src/pages/UserSettings/UserSettings.tsx
  client/src/pages/UserSettings/components/DangerZone.tsx
  client/src/pages/UserSettings/components/SettingsList.tsx
  client/src/styles.ts
Labels: enhancement, frontend

#149 Percentage change fixed when first average is 0
  client/src/pages/Analytics/components/CompareGraph.tsx
Labels: bug, frontend

#148 Fix budget decimal bug
  client/src/pages/Budgets/Components/ProgressBar.tsx
Labels: bug, frontend

#146 Created Acceptance tests
  documentation/acceptence-tests/acceptance-criteria.md
  documentation/acceptence-tests/budget-management-tests.md
  documentation/acceptence-tests/expense-analytics-tests.md
  documentation/acceptence-tests/expense-management-tests.md
  documentation/acceptence-tests/group-expense-splitting-tests.md
  documentation/acceptence-tests/user-managagement-tests.md
Labels: documentation

#147 2023 11 06
  documentation/meeting-logs/2023-11-06.md
Labels: documentation

#150 Fixed acceptance test directory name typo
  documentation/acceptance-tests/acceptance-criteria.md
  documentation/acceptance-tests/budget-management-tests.md
  documentation/acceptance-tests/expense-analytics-tests.md
  documentation/acceptance-tests/expense-management-tests.md
  documentation/acceptance-tests/group-expense-splitting-tests.md
  documentation/acceptance-tests/user-managagement-tests.md
Labels: documentation

#151 Security Analysis with SonarCloud
  .github/workflows/sonarcloud.yml
Labels: infrastructure

#153 clean code smells from sonar cloud
  client/src/assets/constants/constants.ts
  client/src/context/UserContext.tsx
  client/src/interfaces/groupSplitInterfaces.ts
  client/src/pages/Analytics/components/CategoryGraph.tsx
  client/src/pages/Analytics/components/CompareGraph.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseDialog.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseTable.tsx
  client/src/pages/GroupExpenses/GroupExpenses.tsx
  client/src/pages/UserSettings/components/SettingsList.tsx
  server/src/test/unit/routes/users.test.ts
Labels: enhancement

#157 SonarCloud SCM environment and version fix
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: infrastructure

#155 Meeting notes Nov 20
  documentation/meeting-logs/2023-11-20.md
Labels: documentation

#159 Frontend enhancements
  client/src/assets/styles/index.ts
  client/src/assets/styles/styles.ts
  client/src/assets/styles/theme.ts
  client/src/pages/Analytics/components/CategoryGraph.tsx
  client/src/pages/Analytics/components/CompareGraph.tsx
  client/src/pages/Analytics/components/MonthlyExpensesGraph.tsx
  client/src/pages/Budgets/Budgets.tsx
  client/src/pages/Budgets/Components/ProgressBar.tsx
  client/src/pages/Budgets/Components/styles.ts
  client/src/pages/Budgets/styles.ts
  client/src/pages/Expenses/Components/ExpenseTable.tsx
  client/src/pages/Expenses/Expenses.tsx
  client/src/pages/GroupExpenses/Components/GroupExpenseTable.tsx
  client/src/pages/GroupExpenses/GroupExpenses.tsx
  client/src/pages/UserSettings/UserSettings.tsx
  client/src/pages/UserSettings/components/styles.ts
  client/src/pages/UserSettings/styles.ts
Labels: enhancement, frontend

#158 Clean code smells
  client/src/pages/UserSettings/components/SettingsList.tsx
Labels: enhancement

#163 Meeting 11
  documentation/meeting-logs/2023-11-20.md
  documentation/meeting-logs/2023-11-27.md
Labels: documentation

#162 JMeter load testing
  server/load-testing/JMeter.PNG
  server/load-testing/load-testing.jmx
  server/load-testing/load-testing.md
Labels: documentation
