Repository BarbzCodez/Spendr, pull requests merged in 2023-10, with the labels that each got.

#44 Frontend, backend, db, Docker setup
  .gitignore
  .prettierrc
  .vscode/settings.json
  client/.eslintrc.js
  client/Dockerfile
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
  db/init.sql
  docker-compose.yml
  package-lock.json
  package.json
  server/.eslintrc.js
  server/.gitignore
  server/Dockerfile
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20231001195105_init/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/src/app.ts
  server/src/config/config.ts
  server/src/db.ts
  server/src/server.ts
  server/tsconfig.json
Labels: frontend, backend, infrastructure

#47 2023-10-02 meeting notes
  documentation/meeting-logs/2023-10-02.md
Labels: documentation

#48 Updated documentation links and added architecture diagram
  README.md
Labels: documentation

#51 UI Setup
  .prettierrc
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/otherStonks-noBackgrounds.png
  client/src/assets/images/spendr_1.png
  client/src/assets/images/stonks-nobackground.png
  client/src/assets/styles/styles.ts
  client/src/assets/styles/theme.ts
  client/src/components/Header/Header.tsx
  client/src/components/Header/index.ts
  client/src/components/Header/styles.ts
  client/src/index.css
  client/src/index.tsx
  client/src/interfaces/interfaces.ts
  client/src/logo.svg
  client/src/pages/Greetings/Greetings.tsx
  client/src/pages/Greetings/index.ts
Labels: frontend

#46 Add test plan
  README.md
  documentation/test-plan.md
Labels: documentation

#53 meeting notes 2023-10-09
  documentation/meeting-logs/2023-10-09.md
Labels: documentation

#57 Removed /api prefix from endpoints, and add /users prefix to auth
  documentation/test-plan.md
  server/src/app.ts
  server/src/routes/auth.ts
  server/src/test/unit/routes/auth.test.ts
Labels: documentation, backend

#54 Greetings page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/images/stonks-nobackground.png
  client/src/assets/styles/styles.ts
  client/src/assets/styles/theme.ts
  client/src/components/Header/Header.tsx
  client/src/components/Header/styles.ts
  client/src/pages/Greetings/Greetings.tsx
  client/src/pages/Greetings/styles.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/index.ts
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/index.ts
Labels: frontend

#62 Created DB schema in Prisma
  server/prisma/schema.prisma
  server/src/test/unit/routes/auth.test.ts
Labels: database

#55 Adding User Settings Page
  client/src/App.tsx
  client/src/assets/styles/index.ts
  client/src/assets/styles/styles.ts
  client/src/assets/styles/theme.ts
  client/src/components/Header/Header.tsx
  client/src/pages/Greetings/Greetings.tsx
  client/src/pages/UserSettings/UserSettings.tsx
  client/src/pages/UserSettings/components/DangerZone.tsx
  client/src/pages/UserSettings/components/SettingsListItem.tsx
  client/src/pages/UserSettings/components/styles.ts
  client/src/pages/UserSettings/index.ts
  client/src/pages/UserSettings/styles.ts
Labels: frontend

#59 API endpoint for deleting accounts
  server/src/routes/auth.ts
  server/src/test/unit/routes/auth.test.ts
Labels: backend, developer task

#64 Applied prisma migrations
  server/prisma/migrations/20231013224341_main/migration.sql
Labels: database

#68 Authentication bypass when in development
  server/src/middleware/authenticate.ts
  server/src/test/unit/middleware/authenticate.test.ts
Labels: backend

#67 Expenses API routes
  documentation/test-plan.md
  server/src/app.ts
  server/src/config/config.ts
  server/src/routes/auth.ts
  server/src/routes/expenses.ts
  server/src/test/unit/routes/auth.test.ts
  server/src/test/unit/routes/expenses.test.ts
  server/src/types/types.d.ts
Labels: backend, developer task

#66 Applied prisma migrations on server entry
  server/Dockerfile
  server/entrypoint.sh
  server/wait-for-it.sh
Labels: bug, database, infrastructure

#72 Elevated permissions on docker scripts
  server/entrypoint.sh
  server/wait-for-it.sh
Labels: backend, infrastructure

#73 Created error logging
  server/Logs/sysErrorLog.txt
  server/Logs/userErrorLog.txt
  server/src/app.ts
  server/src/middleware/errorHandling.ts
  server/src/routes/auth.ts
  server/src/routes/expenses.ts
Labels: backend, infrastructure

#74 GitHub Actions CI workflow with lint, build, test
  .github/workflows/ci.yml
Labels: infrastructure

#78 Added seperate endpoints for updating username and password
  server/src/routes/auth.ts
  server/src/test/unit/routes/auth.test.ts
Labels: backend

#75 Logout Integration
  client/src/components/Header/Header.tsx
Labels: frontend

#82 Expenses
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/ExpenseAPI.ts
  client/src/api/UserAPI.ts
  client/src/assets/styles/theme.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/components/ExpenseDialog/index.ts
  client/src/components/Header/Header.tsx
  client/src/context/UserContext.tsx
  client/src/interfaces/interfaces.ts
  client/src/pages/Expenses/Components/ExpenseTable.tsx
  client/src/pages/Expenses/Components/styles.ts
  client/src/pages/Expenses/Expenses.tsx
  client/src/pages/Expenses/index.ts
  client/src/pages/Expenses/styles.ts
  client/src/pages/Greetings/Greetings.tsx
  client/src/pages/Login/components/LoginForm.tsx
  server/src/routes/expenses.ts
Labels: frontend

#83 UI cleanup
  client/src/App.tsx
  client/src/components/Header/Header.tsx
  client/src/context/UserContext.tsx
  client/src/interfaces/interfaces.ts
  client/src/pages/Expenses/Expenses.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/UserSettings/UserSettings.tsx
Labels: frontend

#81 Hookup settings
  client/src/api/UserAPI.ts
  client/src/context/UserContext.tsx
  client/src/interfaces/interfaces.ts
  client/src/pages/Login/components/LoginForm.tsx
  client/src/pages/Signup/components/SignupForm.tsx
  client/src/pages/UserSettings/components/DangerZone.tsx
  client/src/pages/UserSettings/components/SettingsListItem.tsx
  client/src/pages/UserSettings/components/styles.ts
  server/src/routes/auth.ts
Labels: frontend

#76 2023 10 16 notes
  documentation/meeting-logs/2023-10-16.md
Labels: documentation

#89 ExpenseTable amount sorting fixed
  client/src/pages/Expenses/Components/ExpenseTable.tsx
Labels: bug, frontend

#88 Removed errorLogging
  server/src/app.ts
  server/src/middleware/errorHandling.ts
  server/src/routes/auth.ts
  server/src/routes/expenses.ts
Labels: infrastructure

#93 Update User Stories
  documentation/project-proposal.md
Labels: documentation

#98 Fix: The user hide all columns
  client/src/pages/Expenses/Components/ExpenseTable.tsx
Labels: bug, frontend

#90 CD configurations
  .docker/client/Dockerfile
  .docker/server/Dockerfile
  .github/workflows/cd.yml
Labels: infrastructure

#97 Expense date added to expense dialog
  client/src/api/ExpenseAPI.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/interfaces/interfaces.ts
  client/src/pages/Expenses/Components/ExpenseTable.tsx
Labels: frontend

#108 change dockerfile paths
  .docker/client/Dockerfile
  .docker/server/Dockerfile
  .github/workflows/cd.yml
Labels: infrastructure

#106 Added developer documentation
  documentation/development.md
Labels: documentation

#105 Create budget api
  server/prisma/schema.prisma
  server/src/app.ts
  server/src/routes/budgets.ts
  server/src/test/unit/routes/budgets.test.ts
Labels: backend, database

#99 Colors fixed
  client/src/assets/styles/theme.ts
  client/src/components/ExpenseDialog/ExpenseDialog.tsx
  client/src/components/Header/Header.tsx
  client/src/pages/Expenses/Components/ExpenseTable.tsx
  client/src/pages/Expenses/Components/styles.ts
  client/src/pages/Login/components/LoginForm.tsx
  client/src/pages/Signup/components/SignupForm.tsx
  client/src/pages/UserSettings/components/SettingsListItem.tsx
  client/src/pages/UserSettings/components/styles.ts
  client/src/pages/UserSettings/styles.ts
Labels: frontend

#110 Fetch users budgets API
  server/src/routes/auth.ts
  server/src/test/unit/routes/auth.test.ts
  server/src/types/budgetTypes.d.ts
  server/src/types/expenseTypes.d.ts
  server/src/utils/expenses.ts
Labels: backend, developer task

#116 Update Migrations
  server/prisma/migrations/20231029220217_main/migration.sql
Labels: database

#114 Analytics UI
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Header/Header.tsx
  client/src/pages/Analytics/Analytics.tsx
  client/src/pages/Analytics/components/CategoryGraph.tsx
  client/src/pages/Analytics/components/CompareGraph.tsx
  client/src/pages/Analytics/components/DailyExpensesGraph.tsx
  client/src/pages/Analytics/components/styles.ts
  client/src/pages/Analytics/index.ts
  client/src/pages/Analytics/styles.ts
Labels: frontend

#117 Markdown lint docs
  documentation/development.md
  documentation/meeting-logs/2023-09-18.md
  documentation/meeting-logs/2023-09-25.md
  documentation/meeting-logs/2023-10-02.md
  documentation/meeting-logs/2023-10-09.md
  documentation/meeting-logs/2023-10-16.md
Labels: documentation

#113 Added Morgan Error logging
  server/Logs/userLog.txt
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/middleware/errorLogging.ts
  server/src/routes/auth.ts
  server/src/routes/budgets.ts
  server/src/routes/expenses.ts
Labels: backend, infrastructure
